"""Official scorer for the tammes-50 problem.

Reads ./submission.csv (id,x,y,z; 50 rows), normalizes each row to the unit
sphere, and writes the score to $HILLCLIMB_RESULT (minimum pairwise angle in
degrees, 0.0 if invalid).
Generated by problems/make_tammes.py — edit the template there.
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

N = 50
TOL = 1e-12


def emit(score: float) -> None:
    """hillclimb's verifier contract: the score is written to the result
    file, not scraped from stdout (coding-agent-authored code shares this stream)."""
    path = Path(os.environ.get("HILLCLIMB_RESULT", "eval_result.json"))
    path.write_text(json.dumps({"split": os.environ.get("HILLCLIMB_SPLIT", "validation"),
                                "score": score}))


def fail(reason: str) -> None:
    print(f"INVALID: {reason}")
    emit(0.0)
    print("val_score: 0.0")
    sys.exit(0)


def main() -> None:
    try:
        df = pd.read_csv("submission.csv")
    except Exception as e:  # noqa: BLE001
        fail(f"cannot read submission.csv: {e}")
    for col in ("id", "x", "y", "z"):
        if col not in df.columns:
            fail(f"missing column {col!r}")
    ids = pd.to_numeric(df["id"], errors="coerce").to_numpy(float)
    if len(df) != N or not np.all(np.isfinite(ids)) or sorted(ids.tolist()) != list(range(N)):
        fail(f"need exactly {N} rows with id 0..{N - 1}")
    pts = df[["x", "y", "z"]].apply(pd.to_numeric, errors="coerce").to_numpy(float)[np.argsort(ids)]
    if not np.all(np.isfinite(pts)):
        fail("non-finite or non-numeric coordinates")
    norms = np.linalg.norm(pts, axis=1)
    if np.any(norms < TOL):
        fail("zero-length vector(s): every row must be a direction")
    pts = pts / norms[:, None]
    gram = np.clip(pts @ pts.T, -1.0, 1.0)
    np.fill_diagonal(gram, -1.0)
    min_angle = float(np.degrees(np.arccos(gram.max())))
    print(f"valid code; min pairwise angle = {min_angle:.8f} deg")
    emit(min_angle)
    print(f"val_score: {min_angle:.8f}")


if __name__ == "__main__":
    main()
