"""Machine-checked output format (hillclimb spaces). Format only — the
geometry (collinear triples, the smallest triangle) stays with the verifier.
Generated by problems/make_heilbronn.py — edit the template there.
"""

from hillclimb import spaces

output = spaces.Table(
    "submission.csv",
    columns={
        "id": spaces.Int(values=range(17), unique=True),
        "x": spaces.Float(low=0.0, high=1.0),
        "y": spaces.Float(low=0.0, high=1.0),
    },
    n_rows=17,
)

if __name__ == "__main__":
    raise SystemExit(spaces.main(output))
