"""Machine-checked output format (hillclimb spaces). Format only — the
capacities and the value are the verifier's. Generated by
problems/make_mknap.py — edit the template there.
"""

from hillclimb import spaces

output = spaces.Table(
    "submission.csv",
    columns={
        "id": spaces.Int(values=range(100), unique=True),
        "take": spaces.Int(values=(0, 1)),
    },
    n_rows=100,
)

if __name__ == "__main__":
    raise SystemExit(spaces.main(output))
