"""Official scorer for the erdos-overlap problem.

Reads ./submission.csv (id,value; 400 rows), validates, and writes the
score to $HILLCLIMB_RESULT (max over lags of ∫ h(x)(1 - h(x + k)) dx; 10000 penalty if invalid — lower is better).
Generated by problems/make_autocorrelation.py — edit the template there.
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

K = 400
PENALTY = 10000.0
TOL = 1e-9


def emit(score: float) -> None:
    """hillclimb's verifier contract: the score is written to the result
    file, not scraped from stdout (coding-agent-authored code shares this stream)."""
    path = Path(os.environ.get("HILLCLIMB_RESULT", "eval_result.json"))
    path.write_text(json.dumps({"split": os.environ.get("HILLCLIMB_SPLIT", "validation"),
                                "score": score}))


def fail(reason: str) -> None:
    print(f"INVALID: {reason}")
    emit(PENALTY)
    print(f"val_score: {PENALTY}")
    sys.exit(0)


def read_values() -> np.ndarray:
    """The K bin values in id order; any malformed submission is a fail()."""
    try:
        df = pd.read_csv("submission.csv")
    except Exception as e:  # noqa: BLE001
        fail(f"cannot read submission.csv: {e}")
    for col in ("id", "value"):
        if col not in df.columns:
            fail(f"missing column {col!r}")
    if len(df) != K or sorted(df["id"].tolist()) != list(range(K)):
        fail(f"need exactly {K} rows with id 0..{K - 1}")
    try:
        values = df.sort_values("id")["value"].to_numpy(float)
    except Exception as e:  # noqa: BLE001
        fail(f"non-numeric value(s): {e}")
    if not np.all(np.isfinite(values)):
        fail("non-finite value(s)")
    return values


W = 2.0 / K  # bin width on [0, 2]


def score_of(h: np.ndarray) -> float:
    """max_k ∫ h(x) (1 - h(x + k)) dx for the step function h with values `h`
    on K equal bins of [0, 2] (h and 1 - h extended by zero outside) — EXACT:
    the cross-correlation of two step functions is piecewise linear with kinks
    at multiples of the bin width, where it equals W * sum_i h[i] (1 - h)[i + m],
    so the maximum over k is the maximum over the K*2 - 1 integer lags."""
    return W * float(np.max(np.correlate(h, 1.0 - h, mode="full")))


def main() -> None:
    h = read_values()
    if np.any(h < -TOL) or np.any(h > 1 + TOL):
        fail("value(s) outside [0, 1]")
    h = np.clip(h, 0.0, 1.0)
    if abs(float(h.mean()) - 0.5) > TOL:
        fail(f"unit mass violated: the mean of the values is {h.mean():.9f}, not 0.5")
    score = score_of(h)
    print(f"valid step function; overlap bound = {score:.8f}")
    emit(score)
    print(f"val_score: {score:.8f}")


if __name__ == "__main__":
    main()
