"""Machine-checked output format (hillclimb spaces). Format only — the
distinct-differences rule and the mark at 0 stay with the verifier.
Generated by problems/make_golomb.py — edit the template there.
"""

from hillclimb import spaces

output = spaces.Table(
    "submission.csv",
    columns={
        "id": spaces.Int(values=range(27), unique=True),
        "mark": spaces.Int(low=0, high=999999),
    },
    n_rows=27,
)

if __name__ == "__main__":
    raise SystemExit(spaces.main(output))
