"""Official scorer for the circle-packing-32 problem.

Reads ./submission.csv (id,x,y,r; 32 rows), validates the packing, and writes
the score to $HILLCLIMB_RESULT (sum of radii, 0.0 if invalid) with one
`instances` entry per circle (its radius) so per-instance views can compare
candidates circle by circle. Same format and tolerance as `circle-packing`
(n = 26), so solutions transfer between the two.
Generated by problems/make_circle_packing.py — edit the template there.
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

N = 32
TOL = 1e-9  # numerical slack on containment/overlap


def emit(score: float, instances: dict | None = None) -> None:
    """hillclimb's verifier contract: the score is written to the result
    file, not scraped from stdout (coding-agent-authored code shares this stream)."""
    payload = {"split": os.environ.get("HILLCLIMB_SPLIT", "validation"), "score": score}
    if instances:
        payload["instances"] = instances  # reserved key: per-circle breakdown of `score`
    path = Path(os.environ.get("HILLCLIMB_RESULT", "eval_result.json"))
    path.write_text(json.dumps(payload))


def fail(reason: str) -> None:
    print(f"INVALID: {reason}")
    emit(0.0)
    print("val_score: 0.0")
    sys.exit(0)


def main() -> None:
    try:
        df = pd.read_csv("submission.csv")
    except Exception as e:  # noqa: BLE001
        fail(f"cannot read submission.csv: {e}")
    for col in ("id", "x", "y", "r"):
        if col not in df.columns:
            fail(f"missing column {col!r}")
    if len(df) != N or sorted(df["id"].tolist()) != list(range(N)):
        fail(f"need exactly {N} rows with id 0..{N - 1}")
    df = df.sort_values("id")
    x = df["x"].to_numpy(float)
    y = df["y"].to_numpy(float)
    r = df["r"].to_numpy(float)
    if not np.all(np.isfinite(x) & np.isfinite(y) & np.isfinite(r)):
        fail("non-finite values")
    if np.any(r < -TOL):
        fail("negative radius")
    r = np.clip(r, 0.0, None)
    inside = (x - r >= -TOL) & (x + r <= 1 + TOL) & (y - r >= -TOL) & (y + r <= 1 + TOL)
    if not np.all(inside):
        fail(f"circle(s) {np.where(~inside)[0].tolist()} outside the unit square")
    dist = np.sqrt((x[:, None] - x[None, :]) ** 2 + (y[:, None] - y[None, :]) ** 2)
    required = r[:, None] + r[None, :]
    overlap = (dist + TOL < required) & ~np.eye(N, dtype=bool)
    if np.any(overlap):
        i, j = np.argwhere(overlap)[0]
        fail(f"circles {i} and {j} overlap (dist {dist[i, j]:.6f} < {required[i, j]:.6f})")
    # growth headroom per circle: distance to the nearest binding constraint
    # (a wall or a neighbour) — small radius + large slack = wasted space
    gaps = dist - required + np.where(np.eye(N, dtype=bool), np.inf, 0.0)
    wall = np.minimum.reduce([x - r, 1 - x - r, y - r, 1 - y - r])
    slack = np.minimum(gaps.min(axis=1), wall)
    weakest = np.argsort(r)[:6]
    print("smallest circles (id: radius / slack): " + ", ".join(f"{i}: {r[i]:.4f} / {slack[i]:.4f}" for i in weakest))
    total = float(r.sum())
    print(f"valid packing; sum of radii = {total:.6f}")
    emit(total, {f"circle-{i:02d}": round(float(r[i]), 6) for i in range(N)})
    print(f"val_score: {total:.6f}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:  # noqa: BLE001 — an invalid submission is the floor, never a crash
        fail(f"unexpected error: {e}")
