"""Behavioral fingerprint for `hillclimb similarity`: the sorted areas of
all C(11,3) triangles a candidate's points span.

The flat submission.csv fingerprint would treat a relabelled or reflected
copy of the same layout as a different one; sorted triangle areas are
invariant to point order and to every isometry of the square, and they are
the objective's own geometry (the smallest entry is the score). Returns None
for anything the scorer would reject, so such candidates stay unpositioned.
Generated by problems/make_heilbronn.py — edit the template there.
"""

from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd

N = 11
TOL = 1e-9


def fingerprint(candidate_dir):
    try:
        df = pd.read_csv(Path(candidate_dir) / "submission.csv")
    except Exception:  # noqa: BLE001 — unreadable output is "no fingerprint"
        return None
    if any(col not in df.columns for col in ("id", "x", "y")):
        return None
    if len(df) != N or sorted(df["id"].tolist()) != list(range(N)):
        return None
    pts = df.sort_values("id")[["x", "y"]].to_numpy(float)
    if not np.all(np.isfinite(pts)) or np.any(pts < -TOL) or np.any(pts > 1 + TOL):
        return None
    areas = [
        0.5
        * abs(
            (pts[j, 0] - pts[i, 0]) * (pts[k, 1] - pts[i, 1])
            - (pts[j, 1] - pts[i, 1]) * (pts[k, 0] - pts[i, 0])
        )
        for i, j, k in combinations(range(N), 3)
    ]
    return sorted(areas)
