"""Official scorer for the mknap-250-10 problem.

Reads ./submission.csv (id,take; 250 rows of 0/1), checks the 10 capacity
constraints against data/items.csv and data/capacities.csv, and writes the
score to $HILLCLIMB_RESULT (the total value of the chosen items; 0.0 if
any constraint is exceeded or the file is malformed — higher is better).
Generated by problems/make_mknap.py — edit the template there.
"""

import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

N = 250
M = 10
PENALTY = 0.0


def emit(score: float) -> None:
    """hillclimb's verifier contract: the score is written to the result
    file, not scraped from stdout (agent-authored code shares this stream)."""
    path = Path(os.environ.get("HILLCLIMB_RESULT", "eval_result.json"))
    path.write_text(json.dumps({"split": os.environ.get("HILLCLIMB_SPLIT", "validation"),
                                "score": score}))


def fail(reason: str) -> None:
    print(f"INVALID: {reason}")
    emit(PENALTY)
    print(f"val_score: {PENALTY}")
    sys.exit(0)


def main() -> None:
    data = Path(__file__).resolve().parent / "data"
    items = pd.read_csv(data / "items.csv").sort_values("id")
    caps = pd.read_csv(data / "capacities.csv")
    weight_cols = [f"w{i + 1}" for i in range(M)]
    values = items["value"].to_numpy(float)
    weights = items[weight_cols].to_numpy(float).T          # M x N
    capacity = caps.set_index("constraint").loc[weight_cols, "capacity"].to_numpy(float)

    try:
        df = pd.read_csv("submission.csv")
    except Exception as e:  # noqa: BLE001
        fail(f"cannot read submission.csv: {e}")
    for col in ("id", "take"):
        if col not in df.columns:
            fail(f"missing column {col!r}")
    if len(df) != N or sorted(df["id"].tolist()) != list(range(N)):
        fail(f"need exactly {N} rows with id 0..{N - 1}")
    take = pd.to_numeric(df.sort_values("id")["take"], errors="coerce").to_numpy(float)
    if not np.all(np.isfinite(take)) or not np.all(np.isin(take, (0.0, 1.0))):
        fail("take must be 0 or 1")

    used = weights @ take
    over = [(weight_cols[i], used[i], capacity[i]) for i in range(M) if used[i] > capacity[i]]
    if over:
        fail("over capacity: " + ", ".join(f"{c} {u:.0f}/{cap:.0f}" for c, u, cap in over))
    total = float(values @ take)
    for i in range(M):
        print(f"{weight_cols[i]}: used {used[i]:.0f} of {capacity[i]:.0f}, slack {capacity[i] - used[i]:.0f}")
    print(f"valid: {int(take.sum())} items; total value = {total:.0f}")
    emit(total)
    print(f"val_score: {total:.0f}")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:  # noqa: BLE001 — an invalid submission is the penalty, never a crash
        fail(f"unexpected error: {e}")
