"""Machine-checked output format (hillclimb spaces). Format only — the
energy is the verifier's. Generated by problems/make_labs.py — edit the template there.
"""

from hillclimb import spaces

output = spaces.Table(
    "submission.csv",
    columns={
        "id": spaces.Int(values=range(60), unique=True),
        "spin": spaces.Int(values=(-1, 1)),
    },
    n_rows=60,
)

if __name__ == "__main__":
    raise SystemExit(spaces.main(output))
