"""Machine-checked output format (hillclimb spaces). Format only — the
distance condition, the no-origin and no-duplicate rules stay with the verifier.
Generated by problems/make_kissing.py — edit the template there.
"""

from hillclimb import spaces

MAX_COORD = 100000000

output = spaces.Table(
    "submission.csv",
    columns={
        "id": spaces.Int(low=0, unique=True),
        "c0": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c1": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c2": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c3": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c4": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c5": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c6": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c7": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c8": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c9": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
        "c10": spaces.Int(low=-MAX_COORD, high=MAX_COORD),
    },
    n_rows=(1, 2000),
)

if __name__ == "__main__":
    raise SystemExit(spaces.main(output))
